### ISSUE TITLE
currency_pair gets back BTC instead of ETH price

### ISSUE THREAD

**Issue by Alkhemeia** [coinbase/coinbase-python#32] opened 2017-02-10 07:53 UTC
If i use client.get_buy_price(currency_pair = 'ETH-EUR') i get back the BTC price instead of the ETH price. Am i doing something wrong or is this a bug?

**Comment by iregina** [comment] 2017-03-10 09:18
@Alkhemeia did you get any updates on this issue?

**Comment by sh6khan** [comment] 2017-03-10 10:28
If you hit `https://api.coinbase.com./v2/prices/ETH-EUR/buy` it will return a response with the right prices. The client should be building the same URI. 

what kind of prices are you seeing?

**Comment by iregina** [comment] 2017-03-10 20:01
@sh6khan Does it also work for ETH-US? Could I just hit https://api.coinbase.com./v2/prices/ETH-US/buy because I don't see a response now.

**Comment by sh6khan** [comment] 2017-03-10 20:02
@iregina it would be `ETH-USD` not `ETH-US`.

**Comment by iregina** [comment] 2017-03-10 20:06
Thank you! @sh6khan

**Comment by c4obi** [comment] 2017-03-19 16:37
I have this same issue too. Is this a bug?

**Comment by klefki** [comment] 2017-04-08 07:14
I fixed this by going into the client.py file and modifying the code to look like this. Works just fine now, however would be nice for the files to come like this. But it's a simple fix that you can do on your own.

`def get_spot_price(self, **params):
    """https://developers.coinbase.com/api/v2#get-spot-price"""
    if 'currency_pair' in params:
        currency_pair = params['currency_pair']
    else:
        currency_pair = 'BTC-USD'
    response = self._get('v2', 'prices', currency_pair, 'spot', data=params)
    return self._make_api_object(response, APIObject)`

And now the command works like so:
`eth_price = client.get_spot_price(currency_pair = 'ETH-USD')`

**Comment by carpenter-mike** [comment] 2017-05-27 16:01
This is fixed in master by f9ed2249865c2012e3b86106dad5f8c6068366ed.

**Comment by achampion** [comment] 2017-09-17 17:54
Doesn't the simpler:

    currency_pair = params.get('currency_pair', 'BTC-USD')

Do the same thing as the `if: ... else:` condition but doesn't `pop`:

    currency_pair = params.pop('currency_pair', 'BTC-USD')

make more sense. You don't need to send it with `data` if you have passed it as part of the `url`.

**Comment by keith24** [comment] 2017-11-29 18:40
I think this has been fixed, but the pip and easy_install packages haven't been updated to reflect it.  

This should probably be tagged as a dupe of #35.

**Comment by Liamhanninen** [comment] 2017-12-24 01:16
So what is the best way to update this fix? Pull Master? Also, is there a schedule for updating the pip package with the fix?

**Comment by sds** [comment] 2018-02-11 07:19
[2.0.7](https://pypi.python.org/pypi?:action=display&name=coinbase&version=2.0.7) was released January 26th 2018.

**Closed by sds** 2018-02-11 07:19 UTC
