### ISSUE TITLE
ImportError: No module named wallet.client

### ISSUE THREAD

**Issue by flyize** [coinbase/coinbase-python#23] opened 2016-03-02 14:47 UTC
I keep getting this error when using the sample code posted here:

https://developers.coinbase.com/docs/wallet/guides/bitcoin-wallet

`from coinbase.wallet.client import Client

SANDBOX_URL = 'https://api.sandbox.coinbase.com'
client = Client(
    '1',
    '1',
    base_api_uri=SANDBOX_URL)`

**Comment by jorilallo** [comment] 2016-03-02 18:06
@flyize I think you might be running an old version of the client, please make sure you have 2.0.x installed. I'm closing the issue as I can't reproduce and tests are passing on this with the current version

**Closed by jorilallo** 2016-03-02 18:06 UTC

**Comment by flyize** [comment] 2016-03-02 18:11
Strange.  Im running Python 2.7.11 and v2.0.6 of coinbase.

**Comment by jorilallo** [comment] 2016-03-02 18:22
Weird, installed freshly from pypi and imports just fine with almost identical python version:

```
⋊> ~/p/coinbase-python on master ◦ vf new python-test                                                                                                                                                                                                                         10:13:48
New python executable in /Users/jorilallo/.virtualenvs/python-test/bin/python
Installing setuptools, pip...done.
⋊> ~/p/coinbase-python on master ◦ pip install coinbase                                                                                                                                                                                                                       10:14:05
Downloading/unpacking coinbase
  Downloading coinbase-2.0.6-py2.py3-none-any.whl
....
    
Successfully installed coinbase six requests pycrypto
Cleaning up...
⋊> ~/p/coinbase-python on master ◦ ipython                                                                                                                                                                                                                                    10:14:44
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from coinbase.wallet.client import Client
```

You might want to check that you're for sure on the latest lib version and there's no old ones haunting - I'm suspecting this as it's failing on finding `wallet`, not `coinbase` which would be inline with 1.x version

**Comment by flyize** [comment] 2016-03-02 18:39
I installed this for the first time yesterday, so I'm positive that I don't have an old version.  I also just installed the coinbase module on my laptop and am getting the same error.  I'm not sure what ipython is, but I see python 2.7.10 in your post.  I think I'll try that version next.

FYI:

C:\Users\cherry>pip show coinbase
---
Metadata-Version: 2.0
Name: coinbase
Version: 2.0.6
Summary: Coinbase API client library
Home-page: https://github.com/coinbase/coinbase-python/
Author: Coinbase, Inc.
Author-email: api@coinbase.com
License: MIT License
Location: c:\python27\lib\site-packages
Requires: six, pycrypto, requests

**Comment by jorilallo** [comment] 2016-03-02 18:47
Ok, not sure if this a windows issue etc, never used python outside osx/linux. If you find the reason, please do let us know and PRs are greatly appreciated :)

**Comment by flyize** [comment] 2016-03-02 18:56
Yeah, I've tried 2.7.10 on my laptop and I'm getting the same error across both devices.  Any chance you have someone with a Windows device that can test?  Although if it really was Windows, surely the issue would have sprung up by now.

**Comment by jorilallo** [comment] 2016-03-02 19:16
Sorry, I don't have a windows device available :( Out of curiosity, can you import anything from `coinbase`?

@maksim-s any ideas on this?

**Comment by gluwa** [comment] 2016-04-06 07:26
I got the same error message for a stupid reason. I named my file 'coinbase.py' while trying to use coinbase library in it. The issue resolved after changing my file name into something other than 'coinbase.py'.

**Comment by pkafei** [comment] 2016-09-04 12:52
I am also receiving `ImportError: No module named wallet.client`. I'm working on OS machine, and did change the name of my script to something other than `coinbase.py`.

**Comment by adriaanjoubert** [comment] 2017-03-16 20:17
I just installed coinbase from PIP in 2017 in getting this on OSX + Python2.7/3.5. What is the solution?

**Comment by cam-pretio** [comment] 2017-03-22 20:36
Hi adriaanjoubert,

I also ran into this issue, the fix that worked for me was to delete anything named coinbase.py (which i had my script saved as) uninstall coinbase through pip, and then reinstall it. Now as long as i name it something other than coinbase.py it works perfect.

**Comment by cminatti** [comment] 2017-11-26 16:37
I had the coinbase.pyc file after I rename the coinbase .py... silly error

**Comment by safetydoor** [comment] 2018-04-11 11:33
我找到了原因，因为我项目的一个文件叫就叫coinbase导致了冲突，换个名字就好。
dont use "coinbase" as a python package or filename
