### ISSUE TITLE
Pagination Tools

### ISSUE THREAD

**Issue by xanderdunn** [coinbase/coinbase-python#42] opened 2017-05-16 23:02 UTC
As far as I can tell, this library provides no way of easily navigating paginated API endpoints.  

The [coinbase-node](https://github.com/coinbase/coinbase-node) API makes it super easy.  See the "Using pagination" section:
```
account.getTransactions(null, function(err, txns, pagination) {
  txns.forEach(function(txn) {
    console.log('my txn: ' + txn.id);
  });
  console.log(pagination.next_uri);
  account.getTransactions(pagination, function(err, txns) {
    txns.forEach(function(txn) {
      console.log('my txn: ' + txn.id);
    });
  });
});
```

**Comment by sds** [comment] 2018-02-11 07:29
Duplicate of #34

**Closed by sds** 2018-02-11 07:29 UTC
Labels: duplicate
